/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modul10;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jk = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Nis = new javax.swing.JTextField();
        Nama = new javax.swing.JTextField();
        Kelas = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        Pr = new javax.swing.JRadioButton();
        Lk = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Alamat = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Hasil = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        Save = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        Refresh = new javax.swing.JButton();
        Edit1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FORM BIODATA SISWA SMK TELKOM");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 0, 480, 60);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("The Real Informatic Schools");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 40, 240, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(130, 0, 650, 110);

        jPanel3.setBackground(new java.awt.Color(204, 0, 0));
        jPanel3.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ISIAN DATA SISWA");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(10, 0, 140, 30);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(10, 120, 240, 30);

        jPanel4.setBackground(new java.awt.Color(204, 0, 0));
        jPanel4.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NIS");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(20, 0, 40, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nama");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(20, 50, 40, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Jenis Kelamin");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(20, 100, 140, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Kelas");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(20, 160, 50, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Email");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(20, 210, 50, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Alamat");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(20, 260, 60, 20);

        Nis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NisActionPerformed(evt);
            }
        });
        jPanel4.add(Nis);
        Nis.setBounds(20, 20, 200, 30);

        Nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaActionPerformed(evt);
            }
        });
        jPanel4.add(Nama);
        Nama.setBounds(20, 70, 200, 30);

        Kelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KelasActionPerformed(evt);
            }
        });
        jPanel4.add(Kelas);
        Kelas.setBounds(20, 180, 200, 30);

        Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailActionPerformed(evt);
            }
        });
        jPanel4.add(Email);
        Email.setBounds(20, 230, 200, 30);

        Jk.add(Pr);
        Pr.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Pr.setForeground(new java.awt.Color(255, 255, 255));
        Pr.setText("Prempuan");
        Pr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrActionPerformed(evt);
            }
        });
        jPanel4.add(Pr);
        Pr.setBounds(120, 120, 100, 30);

        Jk.add(Lk);
        Lk.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Lk.setForeground(new java.awt.Color(255, 255, 255));
        Lk.setText("Laki-Laki");
        Lk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LkActionPerformed(evt);
            }
        });
        jPanel4.add(Lk);
        Lk.setBounds(20, 120, 90, 30);

        Alamat.setColumns(20);
        Alamat.setRows(5);
        jScrollPane2.setViewportView(Alamat);

        jPanel4.add(jScrollPane2);
        jScrollPane2.setBounds(20, 280, 200, 120);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(10, 160, 240, 410);

        jPanel2.setBackground(new java.awt.Color(204, 0, 0));
        jPanel2.setLayout(null);

        Hasil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NIS", "NamaSiswa", "JenisKelamin", "Kelas", "Email", "Alamat"
            }
        ));
        Hasil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HasilMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Hasil);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 490, 370);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(260, 180, 510, 390);

        jPanel6.setBackground(new java.awt.Color(204, 0, 0));
        jPanel6.setLayout(null);

        Save.setText("SAVE");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        jPanel6.add(Save);
        Save.setBounds(10, 10, 90, 30);

        Delete.setText("DELETE");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        jPanel6.add(Delete);
        Delete.setBounds(110, 10, 90, 30);

        Clear.setText("CLEAR");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        jPanel6.add(Clear);
        Clear.setBounds(210, 10, 90, 30);

        Refresh.setText("REFRESH");
        Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshActionPerformed(evt);
            }
        });
        jPanel6.add(Refresh);
        Refresh.setBounds(310, 10, 90, 30);

        Edit1.setText("EDIT");
        Edit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edit1ActionPerformed(evt);
            }
        });
        jPanel6.add(Edit1);
        Edit1.setBounds(410, 10, 90, 30);

        getContentPane().add(jPanel6);
        jPanel6.setBounds(260, 120, 510, 50);

        jLabel11.setIcon(new javax.swing.ImageIcon("D:\\LOGO-TELKOM-SCHOOL-apple.png")); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(10, 0, 110, 120);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel5);
        jPanel5.setBounds(0, 0, 780, 580);

        setSize(new java.awt.Dimension(794, 621));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NisActionPerformed

    private void NamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaActionPerformed

    private void KelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KelasActionPerformed

    private void EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        if("".equals(Nis.getText()) || "".equals(Alamat.getText()) || "".equals(Kelas.getText())
                || "".equals(Nama.getText()) || "".equals(Email.getText())) {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        } else {
                    String JK ="";
                    if(Lk.isSelected()){
                            JK = "L";
                        }else {
                            JK = "P";
                        }
                    
                     String SQL = "INSERT INTO `t_siswa` (`NIS`, `NamaSiswa`, `JenisKelamin`, `Kelas`, `Email`, `Alamat`)"
                                + "VALUES('"+Nis.getText()+"','"+Nama.getText()+"','"+JK+"','"+Kelas.getText()+"','"+Email.getText()+"','"+Alamat.getText()+"')";
                    int status = KoneksiDB.execute(SQL);
                    if (status == 1){
                        JOptionPane.showMessageDialog(this, "Data Berhasil DItambah", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                        selectData();
                    }else{
                        JOptionPane.showMessageDialog(this, "Data gagal ditambah", "Sukses", JOptionPane.WARNING_MESSAGE);
                    }
                }   
       
    }//GEN-LAST:event_SaveActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
       int baris = Hasil.getSelectedRow();
       if(baris != -1){
           String NIS = Hasil.getValueAt(baris, 0).toString();
           String SQL = "DELETE FROM t_siswa WHERE NIS='"+NIS+"'";
           int status = KoneksiDB.execute(SQL);
           if(status==1){
               JOptionPane.showMessageDialog(this, "Data berhasil di hapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
           }else{
           JOptionPane.showMessageDialog(this, "Data gagal dihapus","Gagal", JOptionPane.WARNING_MESSAGE);
            }
       }else{
           JOptionPane.showMessageDialog(this, "Pilih baris data terlebih dahulu", "Error", JOptionPane.WARNING_MESSAGE);
       }
        
// TODO add your handling code here:
    }//GEN-LAST:event_DeleteActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        Nama.setText("");
        Nis.setText("");
        Kelas.setText("");
        Jk.clearSelection();
        Email.setText("");
        Alamat.setText("");
        
// TODO add your handling code here:
    }//GEN-LAST:event_ClearActionPerformed

    private void RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshActionPerformed
       selectData();
        // TODO add your handling code here:
    }//GEN-LAST:event_RefreshActionPerformed
    private void selectData() {
        String kolom[] = {"NIS","NamaSiswa","JenisKelamin","Kelas","Email","Alamat"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM t_siswa";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try {
            while(rs.next()){
                String NIS = rs.getString(1);
                String NamaSiswa = rs.getString(2);
                String JenisKelamin = "" ;
                if ("L".equals(rs.getString(3))){
                    JenisKelamin = "Laki-Laki";
                }else {
                    JenisKelamin = "Perempuan";
                }
                String Kelas = rs.getString(4);
                String Email = rs.getString(5);
                String Alamat = rs.getString(6);
                String data[] = {NIS,NamaSiswa,JenisKelamin,Kelas,Email,Alamat};
                dtm.addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        Hasil.setModel(dtm);
    }       
    
    
    private void PrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrActionPerformed

    private void LkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LkActionPerformed

    private void HasilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HasilMouseClicked
        // TODO add your handling code here:
        int baris = Hasil.getSelectedRow();
        if(baris != -1){
            Nis.setText(Hasil.getValueAt(baris, 0).toString());
            Nama.setText(Hasil.getValueAt(baris, 1).toString());
            if("Laki-Laki".equals(Hasil.getValueAt(baris, 2).toString())){
                Lk.setSelected(true);
            }else{
                Pr.setSelected(true);
            }
            Kelas.setText(Hasil.getValueAt(baris, 3).toString());
            Email.setText(Hasil.getValueAt(baris, 4).toString());
            Alamat.setText(Hasil.getValueAt(baris, 5).toString());
        }
    }//GEN-LAST:event_HasilMouseClicked

    private void Edit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edit1ActionPerformed
         if ("".equals(Nis.getText()) || "".equals(Alamat.getText()) || "".equals(Kelas.getText()) || "".equals(Nama.getText()) || "".equals(Email.getText())){
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        } else {
            String JK = "";
            if (Lk.isSelected()){
                JK = "L";
            } else {
                JK = "P";
            }
            String SQL = "UPDATE t_siswa SET"
                    + "WHERE NamaSiswa='"+Nama.getText()+"',"+ "WHERE JenisKelamin='"+JK+"',"
                    + "WHERE Kelas='"+Kelas.getText()+"',"+ "WHERE Email='"+Email.getText()+"',"
                    + "WHERE Alamat='"+Alamat.getText()+"',"
                    + "WHERE NIS='"+Nis.getText()+"',";
            int status = KoneksiDB.execute(SQL);
            if (status == 0) {
                JOptionPane.showMessageDialog(this, "Data Berhasil di Update", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                        selectData();
            } else {
                JOptionPane.showMessageDialog(this, "Data Gagal di Update", "Sukses", JOptionPane.WARNING_MESSAGE);
            }
        }

// TODO add your handling code here:
    }//GEN-LAST:event_Edit1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Alamat;
    private javax.swing.JButton Clear;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Edit1;
    private javax.swing.JTextField Email;
    private javax.swing.JTable Hasil;
    private javax.swing.ButtonGroup Jk;
    private javax.swing.JTextField Kelas;
    private javax.swing.JRadioButton Lk;
    private javax.swing.JTextField Nama;
    private javax.swing.JTextField Nis;
    private javax.swing.JRadioButton Pr;
    private javax.swing.JButton Refresh;
    private javax.swing.JButton Save;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    
}
